-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 03:10:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema catalogdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `catalogdb` ;

-- -----------------------------------------------------
-- Schema catalogdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catalogdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `catalogdb` ;

-- -----------------------------------------------------
-- Table `catalogdb`.`categorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogdb`.`categorys` ;

CREATE TABLE IF NOT EXISTS `catalogdb`.`categorys` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `nameCategory` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `catalogdb`.`sub_categorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogdb`.`sub_categorys` ;

CREATE TABLE IF NOT EXISTS `catalogdb`.`sub_categorys` (
  `idSubCategory` INT NOT NULL AUTO_INCREMENT,
  `nameSubCategory` VARCHAR(64) NOT NULL,
  `id_Category` INT NOT NULL,
  PRIMARY KEY (`idSubCategory`),
  INDEX `fk_sub_category_category1_idx` (`id_Category` ASC) VISIBLE,
  CONSTRAINT `fk_sub_category_category1`
    FOREIGN KEY (`id_Category`)
    REFERENCES `catalogdb`.`categorys` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `catalogdb`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogdb`.`articles` ;

CREATE TABLE IF NOT EXISTS `catalogdb`.`articles` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `titleArticle` VARCHAR(200) NOT NULL,
  `priceArticle` DOUBLE NOT NULL DEFAULT '0',
  `descriptionArticle` VARCHAR(250) NULL DEFAULT NULL,
  `id_SubCategory` INT NOT NULL,
  `imagesArticle` VARCHAR(750) NULL,
  `isProduct` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idArticle`),
  UNIQUE INDEX `name_UNIQUE` (`titleArticle` ASC) VISIBLE,
  INDEX `fk_article_sub_category1_idx` (`id_SubCategory` ASC) VISIBLE,
  CONSTRAINT `fk_article_sub_category1`
    FOREIGN KEY (`id_SubCategory`)
    REFERENCES `catalogdb`.`sub_categorys` (`idSubCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `catalogdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogdb`.`users` ;

CREATE TABLE IF NOT EXISTS `catalogdb`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(128) NOT NULL,
  `lastName` VARCHAR(128) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `photo` VARCHAR(200) NULL DEFAULT NULL,
  `createdAtUser` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `role` ENUM('User', 'Admin', 'Professional') NOT NULL DEFAULT 'Professional',
  `phoneUser` INT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `catalogdb`.`catalogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogdb`.`catalogs` ;

CREATE TABLE IF NOT EXISTS `catalogdb`.`catalogs` (
  `idCatalog` INT NOT NULL AUTO_INCREMENT,
  `titleCatalog` VARCHAR(128) NOT NULL,
  `addressCatalog` VARCHAR(150) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `imagesCatalog` VARCHAR(750) NULL,
  `activateCatalog` TINYINT NOT NULL DEFAULT '1',
  `homeBased` TINYINT NOT NULL DEFAULT 0,
  `id_User` INT NOT NULL,
  PRIMARY KEY (`idCatalog`),
  INDEX `fk_catalogs_users1_idx` (`id_User` ASC) VISIBLE,
  CONSTRAINT `fk_catalogs_users1`
    FOREIGN KEY (`id_User`)
    REFERENCES `catalogdb`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `catalogdb`.`catalog_has_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogdb`.`catalog_has_articles` ;

CREATE TABLE IF NOT EXISTS `catalogdb`.`catalog_has_articles` (
  `id_Catalog` INT NOT NULL,
  `id_Article` INT NOT NULL,
  `quantityArticle` INT NULL DEFAULT NULL,
  `availableArticle` TINYINT NOT NULL DEFAULT 1,
  `rankArticle` INT NULL,
  PRIMARY KEY (`id_Catalog`, `id_Article`),
  INDEX `fk_catalogue_has_article_article1_idx` (`id_Article` ASC) VISIBLE,
  INDEX `fk_catalogue_has_article_catalogue_idx` (`id_Catalog` ASC) VISIBLE,
  CONSTRAINT `fk_catalogue_has_article_article1`
    FOREIGN KEY (`id_Article`)
    REFERENCES `catalogdb`.`articles` (`idArticle`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_catalogue_has_article_catalogue`
    FOREIGN KEY (`id_Catalog`)
    REFERENCES `catalogdb`.`catalogs` (`idCatalog`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
